### ISSUE TITLE
Verify Kiview on Flathub

### ISSUE THREAD

**Issue by overwatcheddude** [flathub/io.github.nyre221.kiview#1]
You can find the steps here:
https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by Nyre221** [comment]
@overwatcheddude 

Verified

![Schermata_20240421_012004](https://github.com/flathub/io.github.nyre221.kiview/assets/104171042/c2ce06bf-7f8f-4cf8-92d3-185e42dec641)
